"""AI Trigger Routes — generate task files in the vault."""

import logging
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session
from pydantic import BaseModel
from typing import Optional

from database import get_db
from models import Order, Product
from services import vault, audit
from services.ai_processor import process_task

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/trigger", tags=["AI Triggers"])


# ─── Schemas ────────────────────────────────────────────────────────────────

class OrderTriggerRequest(BaseModel):
    order_id: int


class InquiryTriggerRequest(BaseModel):
    customer_name: str
    email: str
    subject: str
    message: str
    order_id: Optional[int] = None
    product_id: Optional[int] = None


class InventoryTriggerRequest(BaseModel):
    product_id: Optional[int] = None
    threshold: int = 10


class ProductTriggerRequest(BaseModel):
    name: str
    description: str
    price: float
    category_id: int
    stock: int = 50
    featured: bool = False
    image_url: str = ""


class PriceUpdateTriggerRequest(BaseModel):
    product_id: int
    new_price: float
    reason: str


# ─── 1. ORDER TRIGGER ──────────────────────────────────────────────────────

@router.post("/order")
async def trigger_order(
    req: OrderTriggerRequest,
    db: Session = Depends(get_db),
    auto_process: bool = Query(False, description="Immediately trigger AI processing"),
):
    """Generate a task file when a new order is placed."""
    order = db.query(Order).filter(Order.id == req.order_id).first()
    if not order:
        raise HTTPException(status_code=404, detail=f"Order #{req.order_id} not found")

    now = datetime.now(timezone.utc)
    timestamp = now.strftime("%Y-%m-%d_%H-%M-%S")
    filename = f"ORDER-{order.id}_{timestamp}.md"

    items_lines = ""
    for item in order.items:
        product = db.query(Product).filter(Product.id == item.product_id).first()
        product_name = product.name if product else f"Product #{item.product_id}"
        items_lines += f"| {product_name} | {item.quantity} | ₹{item.price:,.0f} | ₹{item.price * item.quantity:,.0f} |\n"

    content = f"""# New Order Task

## Status: PENDING

| Field | Value |
|-------|-------|
| **Task Type** | Order Processing |
| **Priority** | High |
| **Created** | {now.strftime("%Y-%m-%d %H:%M:%S UTC")} |
| **Order ID** | #{order.id} |
| **Customer** | {order.customer_name} |
| **Email** | {order.email} |
| **Phone** | {order.phone} |
| **Address** | {order.address}, {order.city} |
| **Total** | ₹{order.total:,.0f} |
| **Order Status** | {order.status} |

## Order Items

| Product | Qty | Price | Subtotal |
|---------|-----|-------|----------|
{items_lines}
## Action Required

- [ ] Verify payment received
- [ ] Confirm order with customer via email
- [ ] Prepare items for packaging
- [ ] Assign shipping carrier
- [ ] Update order status to "confirmed"
- [ ] Send tracking details to customer

## Notes

> Auto-generated by Royal Sparkle AI Trigger System.
> This task was created at order placement. Process within 24 hours.
"""

    filepath = vault.write_task_file("Needs_Action", filename, content)

    # Audit logging
    audit.write_audit_entry(
        source="trigger/order",
        action="task.created",
        entity_type="order",
        entity_id=filename,
        details={"order_id": order.id, "customer": order.customer_name, "total": order.total},
        queue="Needs_Action",
        status="PENDING",
    )
    audit.append_daily_log(
        source="trigger/order",
        action="Task Created",
        details=f"ORDER-{order.id} — {order.customer_name} — ₹{order.total:,.0f}",
        status="PENDING",
    )

    result = {
        "status": "task_created",
        "trigger": "order",
        "order_id": order.id,
        "task_file": filename,
        "path": filepath,
    }

    # Auto-process if requested
    if auto_process:
        try:
            process_result = process_task(filename, db)
            result["auto_processed"] = True
            result["process_result"] = process_result
        except Exception as e:
            result["auto_processed"] = False
            result["process_error"] = str(e)

    return result


# ─── 2. INQUIRY TRIGGER ────────────────────────────────────────────────────

@router.post("/inquiry")
async def trigger_inquiry(
    req: InquiryTriggerRequest,
    db: Session = Depends(get_db),
    auto_process: bool = Query(False, description="Immediately trigger AI processing"),
):
    """Generate a reply plan task file for a customer inquiry."""
    now = datetime.now(timezone.utc)
    timestamp = now.strftime("%Y-%m-%d_%H-%M-%S")
    filename = f"INQUIRY_{timestamp}.md"

    # Build context section
    context_lines = ""
    if req.order_id:
        order = db.query(Order).filter(Order.id == req.order_id).first()
        if order:
            context_lines += f"\n### Related Order\n\n"
            context_lines += f"- **Order #{order.id}** — ₹{order.total:,.0f} — Status: {order.status}\n"
            context_lines += f"- Placed: {order.created_at}\n"

    if req.product_id:
        product = db.query(Product).filter(Product.id == req.product_id).first()
        if product:
            context_lines += f"\n### Related Product\n\n"
            context_lines += f"- **{product.name}** — ₹{product.price:,.0f}\n"
            context_lines += f"- Stock: {product.stock} units\n"
            context_lines += f"- Category: {product.category.name if product.category else 'N/A'}\n"

    content = f"""# Customer Inquiry — Reply Plan

## Status: PENDING

| Field | Value |
|-------|-------|
| **Task Type** | Customer Reply |
| **Priority** | Medium |
| **Created** | {now.strftime("%Y-%m-%d %H:%M:%S UTC")} |
| **Customer** | {req.customer_name} |
| **Email** | {req.email} |
| **Subject** | {req.subject} |

## Customer Message

> {req.message}
{context_lines}
## Reply Plan

### Suggested Response Outline

1. **Acknowledge** — Greet the customer and thank them for reaching out
2. **Address** — Directly answer their question about: _{req.subject}_
3. **Resolve** — Provide a clear solution or next step
4. **Follow-up** — Offer additional help and close warmly

### Tone Guidelines

- Warm and professional
- Use customer's first name: **{req.customer_name.split()[0]}**
- Brand voice: elegant, helpful, feminine

## Action Required

- [ ] Draft reply following the plan above
- [ ] Review reply for accuracy
- [ ] Send reply to {req.email}
- [ ] Mark inquiry as resolved
- [ ] Log interaction in CRM

## Notes

> Auto-generated by Royal Sparkle AI Trigger System.
> Respond within 4 hours during business hours.
"""

    filepath = vault.write_task_file("Needs_Action", filename, content)

    # Audit logging
    audit.write_audit_entry(
        source="trigger/inquiry",
        action="task.created",
        entity_type="inquiry",
        entity_id=filename,
        details={"customer": req.customer_name, "subject": req.subject, "email": req.email},
        queue="Needs_Action",
        status="PENDING",
    )
    audit.append_daily_log(
        source="trigger/inquiry",
        action="Task Created",
        details=f"INQUIRY from {req.customer_name} — \"{req.subject}\"",
        status="PENDING",
    )

    result = {
        "status": "task_created",
        "trigger": "inquiry",
        "customer": req.customer_name,
        "subject": req.subject,
        "task_file": filename,
        "path": filepath,
    }

    if auto_process:
        try:
            process_result = process_task(filename, db)
            result["auto_processed"] = True
            result["process_result"] = process_result
        except Exception as e:
            result["auto_processed"] = False
            result["process_error"] = str(e)

    return result


# ─── 3. INVENTORY TRIGGER ──────────────────────────────────────────────────

@router.post("/inventory")
async def trigger_inventory(
    req: InventoryTriggerRequest,
    db: Session = Depends(get_db),
    auto_process: bool = Query(False, description="Immediately trigger AI processing"),
):
    """Generate an alert task file for low-stock products."""
    now = datetime.now(timezone.utc)
    timestamp = now.strftime("%Y-%m-%d_%H-%M-%S")

    if req.product_id:
        product = db.query(Product).filter(Product.id == req.product_id).first()
        if not product:
            raise HTTPException(status_code=404, detail=f"Product #{req.product_id} not found")
        low_stock = [product] if product.stock < req.threshold else []
    else:
        low_stock = db.query(Product).filter(Product.stock < req.threshold).all()

    if not low_stock:
        return {
            "status": "no_action_needed",
            "trigger": "inventory",
            "message": f"All products are above the {req.threshold}-unit threshold.",
        }

    filename = f"INVENTORY-ALERT_{timestamp}.md"

    product_rows = ""
    critical_count = 0
    for p in low_stock:
        urgency = "CRITICAL" if p.stock <= 3 else ("LOW" if p.stock <= 7 else "WARNING")
        if p.stock <= 3:
            critical_count += 1
        category_name = p.category.name if p.category else "N/A"
        product_rows += f"| {p.id} | {p.name} | {category_name} | {p.stock} | {urgency} |\n"

    priority = "Critical" if critical_count > 0 else "High"

    content = f"""# Inventory Alert — Low Stock

## Status: PENDING

| Field | Value |
|-------|-------|
| **Task Type** | Inventory Restock |
| **Priority** | {priority} |
| **Created** | {now.strftime("%Y-%m-%d %H:%M:%S UTC")} |
| **Threshold** | {req.threshold} units |
| **Products Affected** | {len(low_stock)} |
| **Critical Items** | {critical_count} |

## Low Stock Products

| ID | Product | Category | Stock | Urgency |
|----|---------|----------|-------|---------|
{product_rows}
## Action Required

- [ ] Review low-stock items above
- [ ] Contact suppliers for restock quotes
- [ ] Place restock orders for CRITICAL items immediately
- [ ] Update expected restock dates in system
- [ ] Consider marking out-of-stock items on website
- [ ] Review sales velocity to adjust reorder quantities

## Restock Priority

1. **Immediate** — Items with 0-3 units (CRITICAL)
2. **This Week** — Items with 4-7 units (LOW)
3. **Monitor** — Items with 8-{req.threshold - 1} units (WARNING)

## Notes

> Auto-generated by Royal Sparkle AI Trigger System.
> Critical items should be restocked within 48 hours.
> Review inventory weekly to prevent stockouts.
"""

    filepath = vault.write_task_file("Needs_Action", filename, content)

    # Audit logging
    audit.write_audit_entry(
        source="trigger/inventory",
        action="task.created",
        entity_type="inventory",
        entity_id=filename,
        details={
            "products_affected": len(low_stock),
            "critical_count": critical_count,
            "threshold": req.threshold,
        },
        queue="Needs_Action",
        status="PENDING",
    )
    audit.append_daily_log(
        source="trigger/inventory",
        action="Task Created",
        details=f"INVENTORY-ALERT — {len(low_stock)} products below {req.threshold} units ({critical_count} critical)",
        status="PENDING",
    )

    result = {
        "status": "task_created",
        "trigger": "inventory",
        "products_affected": len(low_stock),
        "critical_count": critical_count,
        "task_file": filename,
        "path": filepath,
    }

    if auto_process:
        try:
            process_result = process_task(filename, db)
            result["auto_processed"] = True
            result["process_result"] = process_result
        except Exception as e:
            result["auto_processed"] = False
            result["process_error"] = str(e)

    return result


# ─── 4. PRODUCT TRIGGER ──────────────────────────────────────────────────────

@router.post("/product")
async def trigger_product(
    req: ProductTriggerRequest,
    db: Session = Depends(get_db),
    auto_process: bool = Query(False),
):
    """Generate a task file to add a new product."""
    now = datetime.now(timezone.utc)
    timestamp = now.strftime("%Y-%m-%d_%H-%M-%S")
    filename = f"PRODUCT-ADD_{timestamp}.md"

    from models import Category
    category = db.query(Category).filter(Category.id == req.category_id).first()
    category_name = category.name if category else f"Category #{req.category_id}"

    content = f"""# New Product Task

## Status: PENDING

| Field | Value |
|-------|-------|
| **Task Type** | Product Addition |
| **Priority** | Medium |
| **Created** | {now.strftime("%Y-%m-%d %H:%M:%S UTC")} |
| **Product Name** | {req.name} |
| **Description** | {req.description} |
| **Price** | ₹{req.price:,.0f} |
| **Category** | {category_name} |
| **Category ID** | {req.category_id} |
| **Stock** | {req.stock} |
| **Featured** | {"Yes" if req.featured else "No"} |

## Action Required

- [ ] Verify product details and pricing
- [ ] Check for duplicate listings
- [ ] Validate category assignment
- [ ] Add product to catalog
- [ ] Update inventory system

## Notes

> Auto-generated by Royal Sparkle AI Trigger System.
> Review and approve before publishing to the storefront.
"""

    filepath = vault.write_task_file("Needs_Action", filename, content)
    audit.write_audit_entry(
        source="trigger/product", action="task.created", entity_type="product",
        entity_id=filename, details={"product_name": req.name, "price": req.price},
        queue="Needs_Action", status="PENDING",
    )
    audit.append_daily_log(
        source="trigger/product", action="Task Created",
        details=f"PRODUCT-ADD — {req.name} — ₹{req.price:,.0f}", status="PENDING",
    )
    result = {"status": "task_created", "trigger": "product", "task_file": filename, "path": filepath}
    if auto_process:
        try:
            process_result = process_task(filename, db)
            result["auto_processed"] = True
            result["process_result"] = process_result
        except Exception as e:
            result["auto_processed"] = False
            result["process_error"] = str(e)
    return result


# ─── 5. PRICE UPDATE TRIGGER ─────────────────────────────────────────────────

@router.post("/price-update")
async def trigger_price_update(
    req: PriceUpdateTriggerRequest,
    db: Session = Depends(get_db),
    auto_process: bool = Query(False),
):
    """Generate a task file to update product pricing."""
    product = db.query(Product).filter(Product.id == req.product_id).first()
    if not product:
        raise HTTPException(status_code=404, detail=f"Product #{req.product_id} not found")

    now = datetime.now(timezone.utc)
    timestamp = now.strftime("%Y-%m-%d_%H-%M-%S")
    filename = f"PRICE-UPDATE_{timestamp}.md"

    content = f"""# Price Update Task

## Status: PENDING

| Field | Value |
|-------|-------|
| **Task Type** | Price Update |
| **Priority** | Medium |
| **Created** | {now.strftime("%Y-%m-%d %H:%M:%S UTC")} |
| **Product ID** | {product.id} |
| **Product Name** | {product.name} |
| **Current Price** | ₹{product.price:,.0f} |
| **New Price** | ₹{req.new_price:,.0f} |
| **Change** | {"+" if req.new_price > product.price else ""}₹{req.new_price - product.price:,.0f} |
| **Reason** | {req.reason} |

## Action Required

- [ ] Verify pricing against margin rules (min 30% margin)
- [ ] Check for active promotions on this product
- [ ] Update price in catalog
- [ ] Notify marketing if significant change

## Notes

> Auto-generated by Royal Sparkle AI Trigger System.
> Price changes require approval before applying.
"""

    filepath = vault.write_task_file("Needs_Action", filename, content)
    audit.write_audit_entry(
        source="trigger/price-update", action="task.created", entity_type="product",
        entity_id=filename, details={"product_id": product.id, "old_price": product.price, "new_price": req.new_price, "reason": req.reason},
        queue="Needs_Action", status="PENDING",
    )
    audit.append_daily_log(
        source="trigger/price-update", action="Task Created",
        details=f"PRICE-UPDATE — {product.name}: ₹{product.price:,.0f} → ₹{req.new_price:,.0f}", status="PENDING",
    )
    result = {"status": "task_created", "trigger": "price-update", "task_file": filename, "path": filepath}
    if auto_process:
        try:
            process_result = process_task(filename, db)
            result["auto_processed"] = True
            result["process_result"] = process_result
        except Exception as e:
            result["auto_processed"] = False
            result["process_error"] = str(e)
    return result
