"""
File System Watcher — monitors AI_Employee/Incoming_Files/ for new PDFs and images,
then generates Markdown task files in Needs_Action/.

Usage:
    python file_watcher.py                    # Normal mode
    python file_watcher.py --dry-run          # Log only, no file writes
    python file_watcher.py --log-level DEBUG  # Verbose logging
"""

import argparse
import logging
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler, FileCreatedEvent

import config
from services import vault, audit

logger = logging.getLogger("file_watcher")

# Supported file extensions
PDF_EXTENSIONS = {".pdf"}
IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".gif", ".bmp", ".tiff", ".webp"}
SUPPORTED_EXTENSIONS = PDF_EXTENSIONS | IMAGE_EXTENSIONS


def _human_readable_size(size_bytes: int) -> str:
    """Convert bytes to human-readable string."""
    for unit in ("B", "KB", "MB", "GB"):
        if size_bytes < 1024:
            return f"{size_bytes:.1f} {unit}" if unit != "B" else f"{size_bytes} {unit}"
        size_bytes /= 1024
    return f"{size_bytes:.1f} TB"


def _classify_file(ext: str) -> str:
    """Return 'PDF' or 'Image' based on extension."""
    return "PDF" if ext.lower() in PDF_EXTENSIONS else "Image"


def _build_task_content(filename: str, file_path: Path) -> str:
    """Generate the Markdown task file content for a detected file."""
    now = datetime.now(timezone.utc)
    ext = file_path.suffix.lower()
    file_type = _classify_file(ext)

    try:
        file_size = _human_readable_size(file_path.stat().st_size)
    except OSError:
        file_size = "Unknown"

    return f"""# File Upload — {filename}

## Status: PENDING

| Field | Value |
|-------|-------|
| **Task Type** | File Upload Review |
| **Priority** | Medium |
| **Created** | {now.strftime("%Y-%m-%d %H:%M:%S UTC")} |
| **Source** | watcher/file-upload |
| **Original File** | {filename} |
| **File Type** | {file_type} |
| **Extension** | {ext} |
| **File Size** | {file_size} |
| **Location** | Incoming_Files/{filename} |

## Summary

> Placeholder: This file was detected by the file system watcher.
> A human or AI agent should review the contents and determine next steps.

## Action Required

- [ ] Review the uploaded file
- [ ] Classify content (invoice, customer document, product image, etc.)
- [ ] Extract relevant information
- [ ] Route to appropriate handler
- [ ] Update task status

## Notes

> Auto-generated by Royal Sparkle File Watcher.
"""


class IncomingFileHandler(FileSystemEventHandler):
    """Handles new file creation events in Incoming_Files/."""

    def __init__(self, dry_run: bool = False):
        super().__init__()
        self.dry_run = dry_run

    def on_created(self, event: FileCreatedEvent):
        if event.is_directory:
            return

        file_path = Path(event.src_path)
        ext = file_path.suffix.lower()

        if ext not in SUPPORTED_EXTENSIONS:
            logger.debug(f"Ignored: {file_path.name} (unsupported extension: {ext})")
            return

        # Small delay to let the file finish writing
        time.sleep(0.5)

        filename = file_path.name
        file_type = _classify_file(ext)
        logger.info(f"Detected: {filename} ({file_type})")

        if self.dry_run:
            task_name = vault.generate_task_filename("FILE-UPLOAD")
            logger.info(f"[DRY RUN] Would create task: {task_name} for {filename}")
            return

        self._create_task(filename, file_path)

    def _create_task(self, filename: str, file_path: Path):
        """Create a Markdown task file in Needs_Action and log to audit."""
        task_filename = vault.generate_task_filename("FILE-UPLOAD")
        content = _build_task_content(filename, file_path)

        try:
            task_path = vault.write_task_file("Needs_Action", task_filename, content)
            logger.info(f"Created task: {task_filename} → {task_path}")
        except Exception as e:
            logger.error(f"Failed to write task file for {filename}: {e}")
            return

        # Audit logging
        try:
            audit.write_audit_entry(
                source="watcher/file-upload",
                action="task.created",
                entity_type="file-upload",
                entity_id=task_filename,
                details={
                    "original_file": filename,
                    "file_type": _classify_file(file_path.suffix.lower()),
                    "extension": file_path.suffix.lower(),
                },
                queue="Needs_Action",
                status="PENDING",
            )
            audit.append_daily_log(
                source="watcher/file-upload",
                action="Task Created",
                details=f"FILE-UPLOAD — {filename} detected in Incoming_Files/",
                status="PENDING",
            )
        except Exception as e:
            logger.warning(f"Audit logging failed for {filename}: {e}")


def main():
    parser = argparse.ArgumentParser(
        description="Royal Sparkle File Watcher — monitors Incoming_Files/ for PDFs and images"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Log detections without creating task files",
    )
    parser.add_argument(
        "--log-level",
        default="INFO",
        choices=["DEBUG", "INFO", "WARNING", "ERROR"],
        help="Set logging verbosity (default: INFO)",
    )
    args = parser.parse_args()

    # Configure logging
    logging.basicConfig(
        level=getattr(logging, args.log_level),
        format="%(asctime)s [%(name)s] %(levelname)s: %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )

    # Ensure directories exist
    config.ensure_vault_dirs()

    watch_dir = config.INCOMING_FILES_DIR
    if not watch_dir.exists():
        logger.info(f"Created watch directory: {watch_dir}")

    mode_label = "DRY RUN" if args.dry_run else "LIVE"
    logger.info(f"File Watcher starting ({mode_label})")
    logger.info(f"Watching: {watch_dir}")
    logger.info(f"Supported: {', '.join(sorted(SUPPORTED_EXTENSIONS))}")
    logger.info(f"Tasks go to: {config.NEEDS_ACTION_DIR}")

    handler = IncomingFileHandler(dry_run=args.dry_run)
    observer = Observer()
    observer.schedule(handler, str(watch_dir), recursive=False)
    observer.start()

    try:
        logger.info("Watcher is running. Press Ctrl+C to stop.")
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        logger.info("Shutting down watcher...")
        observer.stop()
    observer.join()
    logger.info("Watcher stopped.")


if __name__ == "__main__":
    main()
